# NumPy (Numerical Python)

#### Introducción:
NumPy es la biblioteca fundamental para la computación científica en Python. Proporciona objetos de matriz multidimensional y herramientas para trabajar con estas matrices.

## Arrays:
Son estructuras de datos similares a las listas en Python, pero pueden tener cualquier número de dimensiones. Además, los arrays son homogéneos, lo que significa que todos los elementos son del mismo tipo.

In [2]:
# Ejemplo de un array

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print (arr)

[1 2 3 4 5]


## Ejercicios Arrays:

### 1. Creación de Arrays

In [6]:
# Crea un array de una dimensión con los números del 0 al 9.

import numpy as np
arr = np.arange(0, 10, 1)
print(arr)

"""np. arange(inicio, fin, salto) : 
Crea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia desde 
inicio hasta fin tomando valores cada salto""" 

[0 1 2 3 4 5 6 7 8 9]


'np. arange(inicio, fin, salto) : \nCrea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia desde \ninicio hasta fin tomando valores cada salto'

### 2. Cambio de Forma

In [9]:
# Cambia la forma del array anterior para que sea un array bidimensional de 2x5.

arr_reshaped = arr.reshape(2, 5)
print(arr_reshaped)

"""reshape permite cambiar la forma de una matriz sin cambiar los datos. 
Sólo ten presente que cuando usamos esta función, la matriz que queremos producir debe tener
la misma cantidad de elementos que la matriz original."""

[[0 1 2 3 4]
 [5 6 7 8 9]]


'reshape permite cambiar la forma de una matriz sin cambiar los datos. \nSólo ten presente que cuando usamos esta función, la matriz que queremos producir debe tener\nla misma cantidad de elementos que la matriz original.'

### 3. Operaciones Básicas

In [27]:
# Crea dos arrays de tamaño 4 y realiza la suma, resta, multiplicación y división elemento a elemento

arr1 = np.arange(10, 14, 1)
arr2 = np.arange(25, 29, 1)
print("El array uno es: ", arr1)
print("El array dos es: ", arr2)

print(" ")

#SUMA
suma = arr1 + arr2
print("La suma es: ", suma)

print(" ")

#RESTA 
resta = arr1 - arr2
print("La resta es: ", resta)

print(" ")

#Multiplicacion
multi = arr1 * arr2
print("La multiplicacion es: ", multi)

print(" ")

#Division
div = arr1 / arr2
print ("La division es: ", div)

El array uno es:  [10 11 12 13]
El array dos es:  [25 26 27 28]
 
La suma es:  [35 37 39 41]
 
La resta es:  [-15 -15 -15 -15]
 
La multiplicacion es:  [250 286 324 364]
 
La division es:  [0.4        0.42307692 0.44444444 0.46428571]


### 4. Indexación y Segmentación

In [37]:
# Dado el siguiente array, extrae los elementos del índice 3 al 7.

arr = np.arange(10, 21)
print(arr)

aux = arr[3:8]
print(aux)

# Para utilizar los dos puntos se debe definir desde que posicion se quiere iniciar hasta la ultima posicion que se desea + 1
# Por ese motivo coloque 8 ya que el ejercicio me pedia hasta la posicion 7, pero numpy le resta una posicion

[10 11 12 13 14 15 16 17 18 19 20]
[13 14 15 16 17]


### 5. Arrays con Condiciones

In [43]:
# Dado un array, reemplace todos los valores impares por -1 sin cambiar el array original.

arr = np.arange(0, 10, 1)

new_arr = np.where(arr % 2 == 1, -1, arr)

print(arr)
print(new_arr)

#Lo que hace el "arr % 2 == 1" es verificar si el numero es impar, verifica si tiene algun resto la division y si es asi
# lo cambia por -1

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 6. Stack de Arrays

In [48]:
# Dados dos arrays, concatena o apila verticalmente.

arr1 = np.arange(0, 10, 1)
arr2 = np.arange(21, 31, 1)

print(arr1)
print(arr2)
print(" ")
conca = np.vstack((arr1, arr2))
print (conca)

# np.vstack se utiliza para apilar la secuencia de arrays de entrada verticalmente para formar un unico array

[0 1 2 3 4 5 6 7 8 9]
[21 22 23 24 25 26 27 28 29 30]
 
[[ 0  1  2  3  4  5  6  7  8  9]
 [21 22 23 24 25 26 27 28 29 30]]


### 7. Operaciones con Funciones Universales

In [52]:
# Dado un array, calcula la raíz cuadrada de cada uno de sus elementos.

arr = np.array([20, 24, 15, 12, 10])
result = np.sqrt(arr)
print(result)

# Con sqrt se puede calcular la raiz cuadrada de los elementos dentro de un array

[4.47213595 4.89897949 3.87298335 3.46410162 3.16227766]


### 8. Operaciones Estadísticas

In [56]:
# Dado un array, encuentra su media, mediana y desviación estándar.

arr = np.random.randn(100)

print(arr)

print(" ")

print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))

#Con random hacemos que los numeros sean al azar entre el 0 y 1, con randn seleccionamos 100 numeros de nuestra bolsa de numeros al azar

[-1.18488967 -1.18795398 -1.15375372 -0.08753848 -1.75611149  0.27033501
 -0.87400303 -0.44009027  0.89653493 -0.25423943 -0.27811693 -0.3366457
  1.03527285  2.6805234   0.45070931 -0.82306159  0.34496503  0.67202304
  1.51573944 -1.34657911  0.98123192 -0.92935727  0.16302348 -0.51241951
  0.89614225 -0.58784043 -0.643016    1.65329601 -0.77453507 -0.31529005
  0.41008564 -0.66461617  0.18721728 -1.56684776 -0.16354498 -0.76050457
 -0.16921326  0.44101363  0.1940124   0.98961947  0.70796978  0.26678317
 -0.73880885 -0.08881153  0.18093101 -0.88024011  0.87942584  1.44476922
  0.10466462 -2.34336332  0.16703328  0.23983954 -1.46383536 -0.39113083
  1.88748907 -1.68203102 -0.24465309 -0.13699303 -1.02820563  0.13266383
 -0.54990068 -1.27983304  1.66790854 -0.02840411  0.69496736  0.31607945
 -0.22934742  0.82072263  1.09948261 -0.16400151 -0.2419461  -0.78931038
 -2.00945912 -0.90978159  1.13790489 -0.16043324  1.80877499 -0.28144458
 -0.90007378 -0.60458525  0.84853672 -1.21269386  1.

### 9. Matrices y Operaciones de Álgebra Lineal

In [58]:
# Crea dos matrices de 3x3 y calcula el producto

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[9, 8, 7], 
                 [6, 5, 4], 
                 [3, 2, 1]])

product = np.dot(arr1, arr2)
print(product)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### 10. Creación de Arrays a partir de Funciones

In [59]:
# Crea un array de 10x10 donde cada elemento es el resultado de ixj, siendo i el indice de la fila y j el indice de la columna

result = np.fromfunction(lambda i, j: i * j, (10, 10), dtype=int)
print(result)

# fromfunction te permite crear un array (o matriz) basado en una función que tú definas. Esta función se aplica a cada posición o coordenada en el array resultante.

# Con el (10x10) definimos que queremos un array de diez filas y diez columnas.

# Con dtype=int definimos que queremos que los elementos que esten adentro de nuestro array sean numeros enteros

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
